---
- name: Create Dirs for Copied Files
  file:
    path: "{{ item.destination_path | dirname }}"
    state: directory
    mode: "{{ item.directory_mode | default('0750') }}"
    owner: "{{ item.user | default(user) }}"
    group: "{{ item.group | default(group) }}"
  loop: "{{ copy_files }}"

- name: Copy Files
  copy:
    src: "{{ item.source_path }}"
    dest: "{{ item.destination_path }}"
    mode: "{{ item.file_mode | default('0640') }}"
    owner: "{{ item.user | default(user) }}"
    group: "{{ item.group | default(group) }}"
  loop: "{{ copy_files }}"
